version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g pnpm

  pre_build:
    commands:
      - cd apollochat-backend
      - pnpm install

  build:
    commands:
      - pnpm build
      - echo "Setting NODE_ENV to production"
      - export NODE_ENV=production

artifacts:
  base-directory: apollochat-backend
  files:
    - dist/**
    - package.json
    - pnpm-lock.yaml
    - Procfile
    - tsconfig-paths-bootstrap.js
    - tsconfig.json
