version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g pnpm

  pre_build:
    commands:
      - cd apollochat-backend
      - pnpm install --frozen-lockfile

  build:
    commands:
      - pnpm build
      - mkdir ../build-output
      - cp -r dist ../build-output/
      - cp package.json ../build-output/
      - cp pnpm-lock.yaml ../build-output/
      - cp tsconfig.json ../build-output/
      - cp nest-cli.json ../build-output/
      - cp Procfile ../build-output/

artifacts:
  base-directory: build-output
  files:
    - "**/*"
