name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches: [master]
    paths:
      - "apollochat-backend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install backend dependencies
        run: |
          cd apollochat-backend
          pnpm install --frozen-lockfile

      - name: Build backend
        run: |
          cd apollochat-backend
          pnpm build

      - name: Prepare deployment artifacts
        run: |
          mkdir build-output
          cp -r apollochat-backend/dist build-output/
          cp apollochat-backend/package.json build-output/
          cp apollochat-backend/pnpm-lock.yaml build-output/
          cp apollochat-backend/tsconfig.json build-output/
          cp apollochat-backend/nest-cli.json build-output/ || true
          cp apollochat-backend/Procfile build-output/

      - name: Zip backend for Beanstalk
        run: zip -r backend.zip build-output/*

      - name: Upload to S3
        run: |
          aws s3 cp backend.zip s3://elasticbeanstalk-ap-southeast-2-680871074175/backend-${{ github.sha }}.zip

      - name: Create new EB version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name apollochat-backend \
            --version-label github-${{ github.sha }} \
            --source-bundle S3Bucket=elasticbeanstalk-ap-southeast-2-680871074175,S3Key=backend-${{ github.sha }}.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name Apollochat-backend-env \
            --version-label github-${{ github.sha }}
