name: Deploy Frontend to Amplify

on:
  push:
    branches: [master]
    paths:
      - "apollochat-ui/**"

jobs:
  deploy:
    runs-on: ubuntu-latestL

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Trigger Amplify Build
        run: |
          aws amplify start-job \
            --app-id d3ci2d4x0qjky4 \
            --branch-name main \
            --job-type RELEASE
